### ISSUE TITLE
Add links to member logos

### ISSUE THREAD

**Issue by esoterra** [bytecodealliance/bytecodealliance.org#26]
* Will make it easier to navigate to information about members
* Will make it easier to identify members with abstract logos (e.g. DFINITY)

**Comment by disquisitioner** [comment]
Thanks for the suggestion!  As part of updating and revising the Bytecode Alliance website I've incorporated changes to the member logos so they are all now links to the members' home page.  That change is now live on bytecodealliance.org.

**Comment by esoterra** [comment]
Thanks!
