### ISSUE TITLE
A blank logo

### ISSUE THREAD

**Issue by gnh1201** [bytecodealliance/bytecodealliance.org#35]
There is a blank logo.

![image](https://user-images.githubusercontent.com/4439601/174702110-d8447d6d-4a49-464e-a942-8bf5635b35e2.png)

**Comment by peterhuene** [comment]
@gnh1201 Thanks for reporting this to us and my apology that we didn't respond to the issue sooner.

This appears to have since been fixed since you reported it. As such, I am going to close this issue.

Please reopen if the problem persists for you.
